story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story7.urls')),
]

story7/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'story7'

urlpatterns = [
    path('', views.story7, name='story7'),
    path('story8/', views.story8, name='story8'),
    path('index/', views.indexView, name='index'),
    path('login/', LoginView.as_view(), name = 'login_url'),
    path('register/',views.registerView, name='register_url'),
    path('dashboard/', views.dashboardView, name="dashboard_url"),
    path('logout/',LogoutView.as_view(next_page="story7:index"), name="logout_url"),
]

story7/models.py
from django.db import models

# Create your models here.

story7/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

def story7(request):
    return render(request, 'story7.html')

def story8(request):
    return render(request, 'story8.html')

def indexView(request):
    return render(request, 'index.html')

@login_required
def dashboardView(request):
    return redirect('story7:story7')

def login(request):
    return render(request, "login.html")

def registerView(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = UserCreationForm() 
    return render(request, 'register.html', {'form': form})

story7/templates/index.html
<!DOCTYPE html>
{% comment %} {% extends 'navbar.html' %} {% endcomment %}
{% load static %}
<title>Welcome</title>
<link rel="stylesheet" type = "text/css" href = "{% static 'css/story7.css' %}" />
{% block content %}
    <div style="margin-top: 10vw; margin-left: 2vw; margin-right: 2vw;">
    <h1 class="d-flex justify-content-center">Welcome!</h1>
    <div class="d-flex justify-content-center">
        {% if user.is_authencticated %}
            <a href="{% url 'story7:logout_url' %}">Logout</a>
            {% else %}
                <a class="mr-5" href="{% url 'story7:login_url' %}">Login</a>
                <a href="{% url 'story7:register_url' %}">Register</a>
        {% endif %}
    </div>
    </div>
{% endblock %}

story7/templates/register.html
<!DOCTYPE html>
{% comment %} {% extends 'navbar.html' %} {% endcomment %}
{% load static %}
<title>Register</title>
<link rel="stylesheet" type = "text/css" href = "{% static 'css/story7.css' %}" />
{% block content %}
    <div class="jumbotron" style="margin-top: 10vw; margin-left: 2vw; margin-right: 2vw;background-color: white;">
        <h1>Create New Account</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button>REGISTER</button>
    </div>
{% endblock %}

story7/templates/story7.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Profile Rania</title>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
    <link rel="stylesheet" type = "text/css" href = "{% static 'css/story7.css' %}" />

</head>
<body>
    <div class="container">
        <div class="col-md-12">
            <div class="row">
                 <nav class="navbar navbar-expand-md navbar-light nav-home">
                    <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
                        <div class="navbutton navbar-nav">
                            <a class="nav-item nav-link" href="{% url 'story7:story7' %}">Profile</a>
                            <a class="nav-item nav-link" href="{% url 'story7:story8' %}">Books</a>
                            {% if user.is_authenticated %}
                                <a class="nav-item nav-link" href="{% url 'story7:logout_url' %}">Logout</a>
                            {% else %}
                                <a class="nav-item nav-link" href="{% url 'story7:register_url' %}">Register</a>
                                <a class="nav-item nav-link" href="{% url 'story7:login_url' %}">Login</a>
                            {% endif %}
                        </div>
                    </div>
                </nav>
            </div>
            <div class="row">
                <div class="theme-switch">
                    <div class="switch"></div>
                </div>
                <p>Switch theme</p>
            </div>

            <div class="jumbotron" style="margin-top: 2vw; margin-left: 2vw; margin-right: 2vw;">
                <h1 class="d-flex justify-content-center">Selamat Datang, {{user.username}}</h1>
            </div>

            <div class="row">
                <ul class="accordion">
                    <li>
                        <a class="toggle" href="javascript:void(0);">Activities</a>
                        <ul class="inner">
                            <li>Belajar</li>
                            <li>Nugas</li>
                            <li>COMPFEST</li>
                            <li>BEM</li>
                            <li>Asdos</li>
                            <li>Bertahan hidup</li>
                        </ul>
                    </li>
                    
                    <li>
                        <a class="toggle" href="javascript:void(0);">Experiences</a>
                        <ul class="inner">
                            <li>Staf PSDM BEM Fasilkom 2019/2020</li>
                            <li>Staf LO Open House Fasilkom 2019</li>
                            <li>Software Development Intern Indonesia Stock Exchange</li>
                            <li>Staf Direct Marketing COMPFEST 11</li>
                            <li>Staf Humas Educare 2019</li>
                            <li>Staf Dekorasi CGT 2019</li>
                            <li>Staf HumPub Open House Fasilkom 2018</li>
                        </ul>
                    </li>
                    
                    <li>
                        <a class="toggle" href="javascript:void(0);">Achievements</a>
                        <ul class="inner">
                            <li>Bertahan hidup 19 tahun 3 bulan</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="{% static "js/story7.js" %}"></script>

</body>

</html>

story7/templates/story8.html
<!DOCTYPE html>
{% load static %}

<head>
    <title>Search Book</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/story7.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
</head>

<body>
    <div class="container">
        <div class="col-md-12">
            <div class="row">
                 <nav class="navbar navbar-expand-md navbar-light nav-home">
                    <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
                        <div class="navbutton navbar-nav">
                            <a class="nav-item nav-link" href="{% url 'story7:story7' %}">Profile</a>
                            <a class="nav-item nav-link" href="{% url 'story7:story8' %}">Books</a>
                            {% if user.is_authenticated %}
                                <a class="nav-item nav-link" href="{% url 'story7:logout_url' %}">Logout</a>
                            {% else %}
                                <a class="nav-item nav-link" href="{% url 'story7:register_url' %}">Register</a>
                                <a class="nav-item nav-link" href="{% url 'story7:login_url' %}">Login</a>
                            {% endif %}
                        </div>
                    </div>
                </nav>
            </div>

            <div class="row">
                <div class="theme-switch">
                    <div class="switch"></div>
                </div>
                <p>Switch theme</p>
            </div>
            
            <div>
                <p id="judul">Search Your Favorite Book Here</p>
            </div>

            <div class="search-box">
                <input class="search-txt" type="search" id="searchField" name="" value="" placeholder="Type to search">
                <button class="search-btn" type="button" name="button"><i class="fas fa-search"></i></button>
            </div>
            
            <table class="table"></table>
        </div> 

    </div>

    <script src="{% static 'js/story8.js' static %}"></script>
    <script src="{% static 'js/story7.js' static %}"></script>

</body>
</html>